- autoload/iced/message.vim
Looks like there was a misspelling since the file we should be looking for is called `.nrepl-port` I think.
> fix spelling in error message

- autoload/iced/di/channel/neovim.vim
- autoload/iced/nrepl.vim
- message/iced/en.txt
Disconnect and reconnecting works:
```
:IcedConnect | IcedDisconnect | IcedConnect
```
Makes `:IcedReconnect` work if a connection is not already established.
> Reconnecting tweaks

- autoload/iced/nrepl.vim
- autoload/iced/nrepl/op/cider.vim
`a:resp` in `s:one_line_doc()` appears to be a list, rather than a dict:
```
Error detected while processing function <lambda>8[1]..<SNR>73_dispatcher[47]..<SNR>137_one_line_doc:
line    7:
E715: Dictionary required
```
> Handle one_line_doc responses that are lists.

- autoload/iced/nrepl/sync.vim
Steps to reproduce:
1. `iced repl`
2. Open a clojure file and `:IcedConnect`
3. Close the iced repl
4. `:quit` editing
```
Timed out.
Error detected while processing function iced#nrepl#auto#leave[2]..iced#nrepl#disconn
ect[3]..iced#nrepl#sync#session_list:
line    2:
E712: Argument of get() must be a List or Dictionary
Error detected while processing function iced#nrepl#auto#leave[2]..iced#nrepl#disconn
ect:
line    3:
E714: List required
```
> Handle error when quitting and nrepl not running

- doc/vim-iced.txt
This change documents how to remove the automatic cider middleware injection that shadow-cljs does.
See liquidz/vim-iced#82 for why that's an issue.
> Update docs for shadow-cljs 2.8.20

- autoload/iced/nrepl/op/iced.vim
- autoload/iced/nrepl/op/iced/sync.vim
- autoload/iced/nrepl/op/refactor.vim
It's a bit of nitpick, but I think `session` is a more suitable name than `sesion`.
> Fix typo in identifier

- autoload/iced/nrepl/var.vim
This PR fixes the jump to definition whose symbol include single quotes.
Cf. https://clojure.org/reference/reader#_symbols
> Fix jump to def that include single quotes

- autoload/iced/nrepl/var.vim
This PR supports jumping to all var that is Clojure's Symbol.
In [reference about Symbols](https://clojure.org/reference/reader#_symbols),
>Symbols begin with a non-numeric character and can contain alphanumeric characters and *, +, !, -, _, ', ?, <, > and = (other characters may be allowed eventually).
I think that other characters mean `/`, `#`, `%` and `&`. `/` is already included in [iskeyword in Vim8.1](https://github.com/vim/vim/blob/v8.1.0000/runtime/ftplugin/clojure.vim#L20), so I added others to `iskeyword`.
> Support jumping to all Clojure's Symbol

- autoload/iced/nrepl.vim
In vim 8.1, when executing `:IcedConnect`, the following interruption occurred.
```
"iced_temporary" [New File]
Connected.
Press ENTER or type command to continue
```
It's a little bother, so I suggest making the behavior silently. That is, suppress any interruption.
```
Connected.
```
> Make buffer initialization silently

- autoload/iced/di/popup/neovim.vim
This adds two global iced options
1. `g:iced_nvim_popup_winhl` to change the popup winhl attribute
2. `g:iced_nvim_minimal_style` to add 'style': 'minimal' to the win_opts.
> Add options for neovim floating window

- bin/iced
- clj/template/iced.bash
The `iced` command seems to supports not only Clojure CLI but also Leinningen or boot. 
So, adding this kind of option for `iced repl` is not suitable, maybe 🤔. 
How about specifing from env var?
Feel free to close this PR.
This is only a suggestion.
> Add option to iced command for overwrite Clojure CLI command

- autoload/iced/buffer.vim
When vim-iced's output window is open, pressing <kbd>\<C-W\>p</kbd> (alternative window) after `s:scroll_to_bottom` is called in the background brings the user to vim-iced's output window instead of the user's previous alternative window. This PR fixes that problem.
If other changes are needed, please let me know. Also feel free to accept or reject this PR. :)
> Preserve alternative window during s:scroll_to_bottom

- doc/pages/cheatsheet.adoc
Probably want to eventually find a way of automatically generating this table instead of manually finding and adding commands.
I didn't keep the description from the pages as the text ended up a bit too long which makes the cheatsheet harder to skim. So rewrote the descriptions to be a bit smaller.
License: MIT
Signed-off-by: Victor Bjelkholm <git@victor.earth>
> Add more refactoring commands to the cheatsheet

- bin/iced
- clj/template/iced.bash
The script uses `/bin/bash` which isn't compatible with [NixOS][issue]. This updates it to use `/usr/bin/env bash` instead
[issue]: https://github.com/NixOS/nixpkgs/issues/25322
> Updated script to use /usr/bin/env

- doc/vim-iced.txt
Rebel Readline (https://github.com/bhauman/rebel-readline) is a user-friendly REPL that goes well with vim-iced. It only has a local service, so you have to create an nREPL after it's been started. This means you have to embed an nREPL. 
It would be nicer to create an nREPL service in Rebel Readline, but it's too complicated!
Added documentation and example 'user.clj'.
@agriffis came up with this solution at https://github.com/clojure-emacs/cider-nrepl/issues/447#issuecomment-570826543
> Add documentation to embed an nREPL, specifically for Rebel Readline

- bin/iced
- Checks if the version is >= 1.10.1.672
- Uses the appropriate main flags
- Gets rid of the warning "WARNING: When invoking clojure.main, use -M"
> Support newer main invocation for Clojure CLI

- autoload/iced/nrepl/var.vim
I usually remove `.` from `iskeyword` to make word-wise movement easier,
however this can break functions like `jump_to_def` because incomplete symbol.
How about adding those characters to `iskeyword` as an safety guard? Avoid affected by user setting.
> Add . and / to cword iskeyword

- autoload/iced/nrepl/navigate.vim
- doc/pages/navigation.adoc
- doc/vim-iced.txt
- ftplugin/clojure.vim
Hi, this is an preliminary PR, hope to request a feature.
I personally use tabpages more than buffers, and hope we can do `IcedDefJump` alike but open new location with new tab, similar to Vim's `gf` and `CTRL-W gf` variant.
Would you accept such functionality? I think it would be useful, for example, user want to keep their current location but open the jump target other way (e.g., `split` window).
> Proposal to allow doing jump-to-def with new tab

- CHANGELOG.adoc
- autoload/iced/nrepl/eval.vim
- autoload/iced/paredit.vim
- autoload/iced/socket_repl.vim
- doc/pages/configuration/evaluation.adoc
- doc/vim-iced.txt
Modifies the behavior of `:IcedEvalOuterTopList` and  `Plug(iced_eval_outer_top_list)` when the cursor is inside forms that have a root `comment` form. Evaluation will be of the topmost form inside the comment, instead of evaluating all forms in the comment as a `do`.
When the cursor is directly inside the comment form, the current behavior of eval as do is preserved.
As example to illustrate:
```clojure
(comment
(print (📍"Hello"))
(print ("world")))
; => hello
(comment
📍(print ("hello"))
(print ("world")))
; => helloworld
```
> Comment aware eval top

- bin/iced.cmd
I confirmed the example introduced in [the document](https://liquidz.github.io/vim-iced/#quick_start) works on Windows. But I had to install more dependencies:
- MSYS2 (Or any other similar systems such as Cygwin would work).
- The `lein` script in shell script: <https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein>.
- `lein.bat` can't be called by the `iced` shell script.
> Support Windows using MSYS2

- installer/jet.sh
- installer/joker.sh
- installer/zprint-clj.sh
There's no version `1.2.01` on zprint's [releases](https://github.com/kkinnear/zprint/releases) page.
> Bump versions of zprint, jet, joker in installers

- autoload/iced/nrepl.vim
- message/iced/en.txt
- python/bencode.py
The other day I had a cider-nrepl server started inside a project that doesn't have iced-nrepl in it. When I `:IcedConnect` to it, it sent back a 1,201,722-byte bencoded string (I'm not familiar with the nrepl protocol so have no idea what it is; it began with a `d18:changed-namespaces` dict) which froze my nvim for 79 seconds... that's a throughput of 15KB/s and sounds a bit too slow. Profiling shows:
<details>
```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
10  78.780231  78.630764  provider#python3#Call()
8             78.627463  <SNR>292_decode_via_python()
```
```
327019 function calls (255933 primitive calls) in 70.975 seconds
Ordered by: standard name
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000    0.000    0.000 …
```
> Improve evaluation experience for large values

- autoload/iced/clojuredocs.vim
- autoload/iced/nrepl.vim
- autoload/iced/nrepl/auto.vim
- autoload/iced/nrepl/cljs.vim
- autoload/iced/nrepl/document.vim
- autoload/iced/nrepl/eval.vim
- autoload/iced/nrepl/navigate.vim
- autoload/iced/nrepl/ns.vim
- autoload/iced/nrepl/var.vim
- doc/vim-iced.txt
- ftplugin/clojure.vim
- test/nrepl_auto.vim
> Fix evaluation process to use ns parameter

- autoload/iced/nrepl/ns.vim
Steps to reproduce
------------------
1. Enable kondo analysis in `vimrc`:
```vimscript
let g:iced_enable_clj_kondo_analysis = v:true
```
2. In vim, open any file of a clojure project (in my case it was a `deps.edn`, works with `*.clj` files too).
3. Start the repl with `iced repl`.
4. Connect vim to repl with `:IcedConnect`.
5. Press `o` to enter insert mode.
Expected behaviour
------------------
File changes instantly, no errors appear in repl window.
Actual behaviour
----------------
Vim hangs for a couple of seconds, an error shows up in a repl window:
```
ERROR: Unhandled REPL handler exception processing message {:id 11, :code {:paths ["src" "resources"]
:deps {org.clojure/clojure {:mvn/version "1.11.1"}
org.clojure/core.match {:mvn/version "1.0.1"}
hiccup/hiccup {:mvn/version …
```
> Fixed type mismatch in `ns#alias_dict`

- python/bencode.py
This PR fix the error by `SyntaxWarning` on Python 3.12.
I got the following error using Python 3.12.
```
Error detected while processing function iced#repl#connect[7]..iced#nrepl#connect[9]..iced#nrepl#connect#auto[33]..<SNR>166___connect_selected[3]..<SNR>166___connect_nrepl[1]..iced#repl#connect[7]..iced#nrepl#connect[51]..iced#promise#sync[4]..function iced#repl#connect[7]..iced#nrepl#connect[9]..iced#nrepl#connect#auto[33]..<SNR>166___connect_sel
ected[3]..<SNR>166___connect_nrepl[1]..iced#repl#connect[7]..iced#nrepl#connect[51]..iced#promise#sync:
line    4:
E605: Exception not caught: {'throwpoint': 'function iced#repl#connect[7]..iced#nrepl#connect[9]..iced#nrepl#connect#auto[33]..<SNR>166___connect_selected[3]..<SNR>166___connect_nrepl[1]..iced#repl#connect[7]..iced#nrepl#connect[ …
```
> Fix the exception by SyntaxWarning on Python 3.12
